### PR TITLE
Fix for issue 232 - reenable test

### LINKED ISSUE #232: Re-enable tests that manually add a project to the dashboard.
The associated tests need to change in a way that it provides less instability to the test suite.

### PR DESCRIPTION
**Pull request by scottkurz**
Fixes #232

### CODE REVIEW

**Comment by scottkurz** [comment]
Tests seem to have a failure.  I did run them locally.  Will try again.

File: tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java [hunk 1]
```diff
@@ -802,4 +723,56 @@ public void testDefaultJRECompliance() {
...
+     * 
+     * @throws Exception
+     */
+    @Test
+    public void testAddingProjectToDashboardManually() throws Exception {
+
+        IProject iProject = LibertyPluginTestUtils.getProject(NON_DFLT_NAME);
+        String projectName = iProject.getName();
+
+        // Refresh the project through the explorer view to pick up the nature removal.
```
Comment (mezarin) [inline tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java:739]: This comment no longer applies. Also the refreshes on line 740 and 743 are a bit redundant because all you really need is the check on line 746-755.

File: tests/pom.xml [hunk 2]
```diff
@@ -34,7 +34,7 @@
                     <useUIThread>false</useUIThread>
                     <providerHint>junit5</providerHint>
                     <systemProperties>
-                        <org.eclipse.swtbot.search.timeout>20000</org.eclipse.swtbot.search.timeout>
+                        <org.eclipse.swtbot.search.timeout>60000</org.eclipse.swtbot.search.timeout>
```
Comment (mezarin) [inline tests/pom.xml:37]: I would question this change. If a widget is not present within at most 10/20 seconds for this particular set of tests, there are bigger issues that need to be investigated. A side effect of increasing the timeout is that it holds getting the results of a failing (out of sync test/IDE) run a very long time.

**Review by mezarin — COMMENTED** [review]
Hi Scott, I just had a couple of comments.

File: tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java (hunk 1 above)
Comment (scottkurz) [reply tests/src/io/openliberty/tools/eclipse/test/it/LibertyPluginSWTBotMavenTest.java]: OK.  I wonder if I need a refresh of the DB after refreshing the project explorer.  I don't think so but am running the tests now.

**Review by mezarin — APPROVED** [review]
